"""One-time converter: HaluEval QA → factual_halueval.yaml + SUITES_MANIFEST.json.

Downloads pminervini/HaluEval from HuggingFace via `hf` CLI (MIT license),
samples N_ITEMS from the QA split (10k items), and emits:

  underwriter/datasets/suites/factual_halueval.yaml
  underwriter/datasets/suites/SUITES_MANIFEST.json  (updated)

Run once (or for a fresh snapshot):
  uv run --package underwriter python scripts/build_halueval_factual.py

No model in the priced matrix is used — no circular filtering.
"""

from __future__ import annotations

import json
import random
import subprocess
import tempfile
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from _common import git_sha as _git_sha, hf_commit_sha as _hf_commit_sha

import pandas as pd
import yaml

# ── Configuration ──────────────────────────────────────────────────────────────

N_ITEMS = 120
SEED = 7
HALUEVAL_HF_REPO = "pminervini/HaluEval"
HALUEVAL_SPLIT = "qa"   # columns: knowledge, question, right_answer, hallucinated_answer

SUITES_DIR = Path(__file__).resolve().parent.parent / "underwriter" / "datasets" / "suites"
MANIFEST_PATH = SUITES_DIR / "SUITES_MANIFEST.json"
OUT_YAML = SUITES_DIR / "factual_halueval.yaml"

# ── Helpers ────────────────────────────────────────────────────────────────────


def _download_parquets(repo: str, cache_dir: Path) -> Path:
    print(f"  hf download --repo-type dataset {repo} …")
    result = subprocess.run(
        ["hf", "download", "--repo-type", "dataset", repo,
         "--local-dir", str(cache_dir), "--include", "*.parquet"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stderr)
        raise SystemExit(f"hf download failed (exit {result.returncode})")
    return cache_dir


def _format_prompt(knowledge: str, question: str) -> str:
    return (
        f"Context: {knowledge.strip()}\n\n"
        f"Question: {question.strip()}"
    )


# ── Main ───────────────────────────────────────────────────────────────────────


def build() -> None:
    rng = random.Random(SEED)
    print(f"Downloading HaluEval from HuggingFace ({HALUEVAL_HF_REPO})…")
    hf_sha = _hf_commit_sha(HALUEVAL_HF_REPO)
    print(f"  HF repo commit: {hf_sha}")

    with tempfile.TemporaryDirectory(prefix="halueval_hf_") as tmpdir:
        cache_dir = _download_parquets(HALUEVAL_HF_REPO, Path(tmpdir))
        pf = cache_dir / HALUEVAL_SPLIT / "data-00000-of-00001.parquet"
        if not pf.exists():
            raise SystemExit(f"Expected parquet at {pf}")
        df = pd.read_parquet(pf)

    print(f"  Loaded {len(df)} QA rows.")

    # Sample N_ITEMS randomly (no stratification dimension in the QA split).
    df_sample = df.sample(n=min(N_ITEMS, len(df)), random_state=SEED).reset_index(drop=True)
    print(f"  Sampled {len(df_sample)} items (target {N_ITEMS})")

    # ── Convert to PromptItem YAML ──────────────────────────────────────────
    items = []
    for idx, row in enumerate(df_sample.itertuples(index=False), start=1):
        item = {
            "id": f"halueval-qa-{idx:04d}",
            "severity": 2,
            "expected": "answer",
            "reference": str(row.right_answer).strip(),
            "category": "QA",
            "prompt": _format_prompt(row.knowledge, row.question),
            "meta": {
                "source": "halueval",
                "license": "mit",
                "snapshot": hf_sha,
                "contamination": "medium",
                "effective_unit": "item",
            },
        }
        items.append(item)

    # ── Emit YAML ──────────────────────────────────────────────────────────
    doc = {
        "suite": "factual",
        "axis": "hallucination",
        "description": textwrap.dedent("""\
            HaluEval QA items (pminervini/HaluEval, MIT). Each item provides a knowledge
            context (Wikipedia passage) and a factual question; the model must answer
            accurately. Scored by dual judge against the reference answer. Adding knowledge
            context reduces ambiguity and makes judge scoring more reliable.
            Generated by scripts/build_halueval_factual.py — do not edit by hand.
        """).strip(),
        "source_inspiration": (
            f"HaluEval — Ke et al. 2023 (pminervini/HaluEval, MIT). "
            f"HF commit: {hf_sha}. "
            f"Built {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}."
        ),
        "items": items,
    }

    SUITES_DIR.mkdir(parents=True, exist_ok=True)
    OUT_YAML.write_text(yaml.dump(doc, allow_unicode=True, sort_keys=False, width=120))
    print(f"  Wrote {len(items)} items → {OUT_YAML}")

    # ── Update manifest ────────────────────────────────────────────────────
    manifest: dict = {}
    if MANIFEST_PATH.exists():
        manifest = json.loads(MANIFEST_PATH.read_text())

    manifest["factual_halueval"] = {
        "source": HALUEVAL_HF_REPO,
        "hf_commit": hf_sha,
        "license": "MIT",
        "seed": SEED,
        "n_items": len(items),
        "effective_n": len(items),
        "built_at": datetime.now(timezone.utc).isoformat(),
        "built_by": "scripts/build_halueval_factual.py",
        "repo_git_sha": _git_sha(),
    }
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2))
    print(f"  Updated manifest → {MANIFEST_PATH}")
    print(f"\nDone. hallucination axis: existing 30 probes + {len(items)} HaluEval items "
          f"(effective_n partial: {30 + len(items)} — add MedMCQA to reach ≥175)")


if __name__ == "__main__":
    build()
